name: ArisTeams
version: 1.0
main: me.aris.aristeam.ArisTeams
api-version: 1.20
author: VennLMAO
description: Plugin quản lý Team chuyên nghiệp cho Aris Network

folia-supported: true

commands:
  team:
    description: Lệnh chính của ArisTeams
    aliases: [t, teams, clan]
    usage: /team <subcommand>

permissions:
  aristeams.user:
    description: Quyền cơ bản để sử dụng lệnh team
    default: true
  aristeams.admin:
    description: Quyền cho Admin (reload, quản lý team)
    default: op
